### ISSUE TITLE
Not able to show archived site  

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/swap#41] opened 2022-03-03 16:47 UTC
I have reported SWAP cannot play video and audio from captured site. Now, I encountered archived site not showing properly in SWAP but it is fine in Archive-IT WBM even the site doesn't have audio and video.

Here is the link to the wayback machine in Archive-It 
https://wayback.archive-it.org/18713/20220225003749/https://www.surveymonkey.com/results/SM-H3TP2PSX/

Here is the link to SWAP (Stanford Web Archive Portal)
https://swap.stanford.edu/20220225003741/https://www.surveymonkey.com/results/SM-H3TP2PSX/

**Comment by lwrubel** [comment] 2022-05-18 12:40
[Bug fix released with pywb 2.6.7](https://github.com/webrecorder/pywb/pull/710) has fixed this issue, as reported by @edsu. We locally confirmed these WARCs displayed, but confirm once pywb instance is set up.

**Comment by lwrubel** [comment] 2022-06-15 14:36
@peterchanws, would you review these sites at https://was-pywb-prod.stanford.edu?

**Comment by peterchanws** [comment] 2022-06-15 15:09
Great! I can see the site in https://was-pywb-prod.stanford.edu/

**Comment by lwrubel** [comment] 2022-06-15 15:31
Thanks for confirming. I'll close this ticket since the problem is resolved with pywb.

**Closed as completed by lwrubel** 2022-06-15 15:31 UTC
Labels: web archiving
